app = 'ephemeral-pricing-oracle-pyth-lazer'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
