[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
dummy_transfer = "58yUmvFtbxoV9dRmv3mbrmKCviJmQLY2MzECCa5cWR6j"

[programs.localnet]
dummy_transfer = "58yUmvFtbxoV9dRmv3mbrmKCviJmQLY2MzECCa5cWR6j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "tests/fixtures/Ronu3E8L69WiucfGhBdFviKtuaWDCX7GK3xSEjn6hRd.json"

[scripts]
test = "NODE_OPTIONS='--no-deprecation' yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
program = "tests/fixtures/dlp.so"
upgradeable = false
