[toolchain]
anchor_version = "1.0.2"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
ephemeral_account_chats = "5kUATzj39y1HfMJbkW9tH3nWoLgq3WJ1scwiFdfDrdVT"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"

[hooks]
