# fly.toml app configuration file generated for solana-gpt-oracle on 2024-12-13T21:41:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'solana-gpt-oracle'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
